### PR TITLE
ENH: fast Gini function, 15x speedup for large arrays

### PR DESCRIPTION
**Pull request by vkhodygo**
It seems to be working, however, I checked the results for one short array only. Try running more tests.

### CODE REVIEW

**Review by ArthurVM — COMMENTED** [review]
The new function was giving different results to the original. I will run further tests and see if I can make adjustments.

Some incompatibility of argparse syntax with python3.

**Comment by vkhodygo** [comment]
OK, I've fixed the problem.
I worked with the initial data instead of its sorted version, that caused correct results in tests with sorted data and incorrect results otherwise.
Now the difference between the old and the new versions is either 0 or ~1.e-16
Next step for you is to merge it somehow.

**Review by ArthurVM — COMMENTED** [review]
This fixes the issue and results in a 2-8x speedup, depending on array size.

I will implement this into the newer version of this script.

**Review by ArthurVM — APPROVED** [review]

**Comment by vkhodygo** [comment]
Hah, that also means that my numpy build is much faster in this particular case. 
I need to be more careful with numbers.

**Comment by ArthurVM** [comment]
doesn't really matter, the speedup is still significant! Cheers bro

**Pull request merged**
